name: Java CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 8
          cache: maven
      - name: list files in current directory
        run: ls
      - name: Build with Maven
        run: mvn -B package --file pom.xml
