name: Java CI

on:
  push:
    branches: [ $default-branch, "main-**"  ]
  pull_request:
    branches: [ $default-branch, "main-**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 8
          cache: maven
      - name: Install xmllint
        run: sudo apt -y install libxml2-utils
      - name: Clean maven
        run: mvn -B clean
      - name: import pcond
        run: bash src/main/build_tools/import-pcond.sh
      - name: Build with Maven
        run: mvn -B compile test package --file pom.xml
