name: Java CI

on:
  push:
    branches: [ $default-branch, "main-**"  ]
  pull_request:
    branches: [ $default-branch, "main-**" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 8
          cache: maven
      - name: list files in current directory
        run: ls
      - name: Build with Maven
        run: mvn -B clean generate-sources compile test package --file pom.xml
